language: objective-c

before_install:
 - wget http://download.mono-project.com/archive/3.2.3/macos-10-x86/MonoFramework-MDK-3.2.3.macos10.xamarin.x86.pkg
 - sudo installer -pkg "MonoFramework-MDK-3.2.3.macos10.xamarin.x86.pkg" -target /
 - export EnableNuGetPackageRestore="true"
 - git submodule update --init --recursive
 - mono --runtime=v4.0 .nuget/NuGet.exe install NUnit.Runners -Version 2.6.1 -o packages

script:
  - xbuild
  - mono --runtime=v4.0 packages/NUnit.Runners.2.6.1/tools/nunit-console.exe -exclude=BreaksMono ./MaxMind.Db.Test/bin/Debug/MaxMind.Db.Test.dll

notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "TCbCICRprgO9KdJrwTtkoiyKbN3mp1NjK8j5+fHMsHaHh9sVafVrGL0DKoR3WJOeVhNa2lzSyr0YHeYsqUIEVWnTy0nrt/qNMOsTwX/UPDdVgLEsWp+zf8xID5sXZHBdnDJU1arGsZH449NOuvh3DmgqeocLzrWku5dC/Ts5ZEQ="

addons:
  coverity_scan:
    project:
      name: "maxmind/MaxMind-DB-Reader-dotnet"
      description: "Build submitted via Travis CI"
    notification_email: dev@maxmind.com
    build_command_prepend: "xbuild /t:Clean"
    build_command:   "xbuild /t:Rebuild"
    branch_pattern: .*coverity.*
